### ISSUE TITLE
npm install launch command nmc fails to start

### ISSUE THREAD

**Issue by AddictArts** [azproduction/node-mc#5]
```
JP-LT2:~ admin$ nmc
module.js:338
    throw err;
          ^
Error: Cannot find module '/usr/local/bin/nmc.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Note browsing to node_modules/node-mnc and doing a $ npm start launches without error. Except I have the issue https://github.com/azproduction/node-mc/issues/4

**Comment by azproduction** [comment]
I did fix that issue `node-mc@0.2.3`, but something strange appears from babel side. It seems that some live transformations are not applied in global installation, however in `--production` mode everything is fine.

```
nmc
/usr/local/lib/node_modules/node-mc/server/node-mc.js:1
(function (exports, require, module, __filename, __dirname) { import koa from
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/node-mc/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-mc/server/index.js:3:18)
    at Module._compile (module.js:460:26)
```

Anyway it is unusable in phantomjs due to bugs in font rendering. 
I would ask you to try it in debug mode `npm run debug`.
